#!/usr/bin/env ruby
# 
# Copyright (c) 2012 FadingRed LLC
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 

require 'fileutils'

class Packager < Object
	def run
		puts "Building project (this may take a while)..."
		command = %w(xcodebuild) +
			%w(-target Package) +
			%w(-configuration Release) +
			%w(-project Framework/Greenwich.xcodeproj)
		File.open "greenwich.build", :mode => "w" do |output|
			IO.popen command + [:err=>[:child, :out]] do |io|
				begin
					while line = io.readline
						output.write line
						puts line if line =~ /^(Test|warning:)/
					end
				rescue EOFError
					# finished reading
				end
			end
		end
		raise Exception.new("Build failed") if $?.exitstatus != 0
		puts "Packaging complete."
	end
	
	def build
		outdir = File.join ENV["PROJECT_DIR"], '..'
		version = ENV["GREENWICH_VERSION"]
		scripts = File.join ENV["PROJECT_DIR"], "Scripts"
		readme = File.join ENV["PROJECT_DIR"], "PackageReadme.md"
		license = File.join ENV["PROJECT_DIR"], "..", "License"
		mac = [File.join(ENV["BUILT_PRODUCTS_DIR"], "Greenwich.framework"), scripts]
		ios = [File.join(ENV["BUILT_PRODUCTS_DIR"] + "-iphoneos", "Greenwich.framework"), scripts]
		tools = [File.join(ENV["BUILT_PRODUCTS_DIR"], "Greenwich Translator.app"), File.join(ENV["BUILT_PRODUCTS_DIR"], "Proofer.app")]
		archive = File.join outdir, "greenwich_#{version}.tbz"
		archive_dsym = File.join outdir, "greenwich_#{version}.dsym.tbz"
		
		if ENV["CONFIGURATION"] == "Release"
			puts "creating packages..."
			Dir.chdir File.join ENV["BUILT_PRODUCTS_DIR"], ".." do
				FileUtils.rm_rf "Greenwich"
				FileUtils.mkdir_p "Greenwich/Tools"
				FileUtils.mkdir_p "Greenwich/Mac"
				FileUtils.mkdir_p "Greenwich/iOS"
				mac.each { |file| system "cp", "-R", file, "Greenwich/Mac/" }
				ios.each { |file| system "cp", "-R", file, "Greenwich/iOS/" }
				tools.each { |file| system "cp", "-R", file, "Greenwich/Tools/" }
				FileUtils.cp readme, "Greenwich/Readme"
				FileUtils.cp license, "Greenwich/License"
				tbz ["Greenwich"], :output => archive
			end
			Dir.chdir File.join ENV["BUILT_PRODUCTS_DIR"] do
				tbz Dir.glob("*.dSYM"), :output => archive_dsym
			end
		else
			puts "need to build as a release!"
			exit 1
		end
	end
	
	private
	
	def zip(files, options={})
		output = options[:output]
		output = File.basename(files[0]) unless output
		command = %w(zip -ryq) + [output] + files
		raise Exception.new("Archive failure") unless system *command
	end

	def tbz(files, options={})
		output = options[:output]
		output = File.basename(files[0]) unless output
		command = %w(tar cjf) + [output] + files
		raise Exception.new("Archive failure") unless system *command
	end
end

if __FILE__ == $PROGRAM_NAME
	if ARGV.length == 1 && ARGV[0] == "build"
		Packager.new.build
	elsif ARGV.length == 0
		Packager.new.run
	else
		$stderr.puts "usage: package [build]"
		exit 1
	end
end
